// Package autoload generates the pre-computed vendor/autoload.php from PSR-4
// namespace maps without requiring a live `composer install`.
//
// The generated autoload.php registers a single PSR-4 autoloader via
// spl_autoload_register(). Given the list of installed packages and their
// PSR-4/classmap entries extracted from each package's composer.json, the
// generator produces a self-contained PHP file that works without the real
// Composer runtime.
//
// Usage:
//
//	src := autoload.Generate(entries)
//	// Write src to vendor/autoload.php
package autoload

import (
	"fmt"
	"sort"
	"strings"
)

// PSR4Entry describes one PSR-4 namespace mapping from a Composer package.
type PSR4Entry struct {
	// Prefix is the PHP namespace prefix including trailing backslash,
	// e.g. "GuzzleHttp\\".
	Prefix string
	// Dir is the path to the source directory relative to vendor/,
	// e.g. "guzzlehttp/guzzle/src".
	Dir string
}

// ClassmapEntry maps a fully-qualified class name to a file path.
type ClassmapEntry struct {
	// FQCN is the fully-qualified class name, e.g. "GuzzleHttp\\Client".
	FQCN string
	// File is the path to the class file relative to vendor/,
	// e.g. "guzzlehttp/guzzle/src/Client.php".
	File string
}

// FilesEntry is an always-include file (like Composer's "files" autoload).
type FilesEntry struct {
	// File is the path relative to vendor/, e.g. "vendor/helpers.php".
	File string
}

// Config holds all autoload data for Generate().
type Config struct {
	// PSR4 is the list of PSR-4 namespace prefix -> directory mappings.
	PSR4 []PSR4Entry
	// Classmap is the list of explicit FQCN -> file mappings.
	Classmap []ClassmapEntry
	// Files is the list of always-include files.
	Files []FilesEntry
}

// Generate produces the PHP source text for a vendor/autoload.php file.
// The generated file registers a PSR-4 autoloader and optionally includes
// always-include files.
func Generate(cfg Config) string {
	// Sort for determinism.
	sorted4 := make([]PSR4Entry, len(cfg.PSR4))
	copy(sorted4, cfg.PSR4)
	sort.Slice(sorted4, func(i, j int) bool {
		return sorted4[i].Prefix < sorted4[j].Prefix
	})

	sortedCM := make([]ClassmapEntry, len(cfg.Classmap))
	copy(sortedCM, cfg.Classmap)
	sort.Slice(sortedCM, func(i, j int) bool {
		return sortedCM[i].FQCN < sortedCM[j].FQCN
	})

	var sb strings.Builder
	sb.WriteString("<?php\n")
	sb.WriteString("declare(strict_types=1);\n\n")
	sb.WriteString("// Mochi PHP bridge -- pre-computed vendor/autoload.php\n")
	sb.WriteString("// Generated by mochi build; do not edit manually.\n\n")

	// Always-include files.
	if len(cfg.Files) > 0 {
		for _, f := range cfg.Files {
			fmt.Fprintf(&sb, "require_once __DIR__.'/%s';\n", f.File)
		}
		sb.WriteString("\n")
	}

	// PSR-4 autoloader.
	if len(sorted4) > 0 || len(sortedCM) > 0 {
		sb.WriteString("spl_autoload_register(function (string $class): void {\n")

		if len(sorted4) > 0 {
			sb.WriteString("    static $psr4 = [\n")
			for _, e := range sorted4 {
				fmt.Fprintf(&sb, "        %q => __DIR__.'/%s',\n", e.Prefix, e.Dir)
			}
			sb.WriteString("    ];\n\n")
			sb.WriteString("    foreach ($psr4 as $prefix => $dir) {\n")
			sb.WriteString("        $len = strlen($prefix);\n")
			sb.WriteString("        if (strncmp($class, $prefix, $len) !== 0) {\n")
			sb.WriteString("            continue;\n")
			sb.WriteString("        }\n")
			sb.WriteString("        $rel = substr($class, $len);\n")
			sb.WriteString("        $file = $dir . '/' . str_replace('\\\\', '/', $rel) . '.php';\n")
			sb.WriteString("        if (is_file($file)) {\n")
			sb.WriteString("            require $file;\n")
			sb.WriteString("            return;\n")
			sb.WriteString("        }\n")
			sb.WriteString("    }\n")
		}

		if len(sortedCM) > 0 {
			if len(sorted4) > 0 {
				sb.WriteString("\n")
			}
			sb.WriteString("    static $classmap = [\n")
			for _, e := range sortedCM {
				fmt.Fprintf(&sb, "        %q => __DIR__.'/%s',\n", e.FQCN, e.File)
			}
			sb.WriteString("    ];\n\n")
			sb.WriteString("    if (isset($classmap[$class])) {\n")
			sb.WriteString("        require $classmap[$class];\n")
			sb.WriteString("    }\n")
		}

		sb.WriteString("});\n")
	}

	return sb.String()
}

// BuildConfig constructs a Config from a list of package autoload data.
// pkgs is a slice of PackageAutoload structs describing each installed package.
func BuildConfig(pkgs []PackageAutoload) Config {
	cfg := Config{}
	for _, pkg := range pkgs {
		for prefix, dir := range pkg.PSR4 {
			cfg.PSR4 = append(cfg.PSR4, PSR4Entry{
				Prefix: normalisePrefix(prefix),
				Dir:    pkg.VendorDir + "/" + strings.TrimSuffix(dir, "/"),
			})
		}
		for fqcn, file := range pkg.Classmap {
			cfg.Classmap = append(cfg.Classmap, ClassmapEntry{
				FQCN: fqcn,
				File: pkg.VendorDir + "/" + file,
			})
		}
		for _, file := range pkg.Files {
			cfg.Files = append(cfg.Files, FilesEntry{
				File: pkg.VendorDir + "/" + file,
			})
		}
	}
	return cfg
}

// PackageAutoload holds the autoload data extracted from one package's composer.json.
type PackageAutoload struct {
	// VendorDir is the package's subdirectory under vendor/, e.g. "guzzlehttp/guzzle".
	VendorDir string
	// PSR4 maps namespace prefix -> source directory (within VendorDir).
	PSR4 map[string]string
	// Classmap maps FQCN -> file path (within VendorDir).
	Classmap map[string]string
	// Files is the list of always-include file paths (within VendorDir).
	Files []string
}

// normalisePrefix ensures a PSR-4 prefix ends with a backslash.
func normalisePrefix(prefix string) string {
	if !strings.HasSuffix(prefix, "\\") {
		return prefix + "\\"
	}
	return prefix
}
